version: '2'
services:
   db:
      build: ./mysql
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD:root
        MYSQL_USER: dev
        MYSQL_PASSWORD: root
        MYSQL_DATABASE: mydatabase
    tomcat:
      build: ./tomcat
      ports:
        - '8080:8080'    

    fastdfs:
      build: ./fastdfs
          # 该容器是否需要开机启动+自动重启。若需要，则取消注释。
          # restart: always
          container_name: fastdfs
          environment:
              # docker所在主机的IP地址
              - IP=127.0.0.1
          volumes:
              # 将本地目录映射到docker容器内的fastdfs数据存储目录
              - ${HOME}/docker-data/fdfs:/var/local/fdfs
          # 使docker具有root权限以读写主机上的目录
          privileged: true
          # 网络模式为host，即直接使用主机的网络接口
          network_mode: "host"    
    nginx:
        build: ./nginx
        ports:
         - "80:80"
        environment:
         - NGINX_HOST=foobar.com
         - NGINX_PORT=80     

    redis:
        image: 'bitnami/redis:4.0'
        environment:
          # ALLOW_EMPTY_PASSWORD is recommended only for development.
          - ALLOW_EMPTY_PASSWORD=yes
          - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
        ports:
          - '6379:6379'
        volumes:
          - 'redis_data:/bitnami'

        volumes:
          redis_data:
          driver: local        
    hbase:
        image: harisekhon/hbase:${VERSION:-latest}
        ports:
          - 2181:2181
          - 8080:8080
          - 8085:8085
          - 9090:9090
          - 9095:9095
          - 16000:16000
          - 16010:16010
          - 16201:16201
          - 16301:16301